// Editorial notes describe visible design decisions, not measured research outcomes.
window.portfolioProjects = [
{"id":"vanguard","name":"Vanguard · Concept revisited","title":"Choose your role. Enter with confidence.","category":"Game UI","context":"Old concepts revisited · Medieval game UI","originalPeriod":"Date unconfirmed","dateKind":"Supplied concept","dateBasis":"The user supplied the starting image as an older concept to revisit; its original date and production context are unconfirmed. Companion screens created in 2026.","summary":"Revisiting an atmospheric class-selection concept as a complete preparation journey. Three new screens preserve the steel, smoke, and heraldry while making class trade-offs, equipment changes, and deployment easier to understand.","tags":["Concept revival","Loadout UX","Interaction states"],"frames":[{"src":"vanguard/original.png","label":"Starting concept","title":"A strong world. An unclear decision.","note":"The supplied concept establishes a striking medieval identity, but repeated 9 ratings lack a visible scale, class rank resembles a combat attribute, and equipment cards do not name the items or distinguish equipped from selected. Fight also leaves the transition unclear. These observations inform the revisit; they are not findings from user testing.","focus":"Retain the atmosphere; clarify the information behind the choice."},{"src":"vanguard/class-selection.png","generated":true,"label":"Class selection","title":"Explain the role before the numbers.","note":"Reach, mobility, and protection describe the proposed class trade-off. A short role statement supports newcomers, while named equipment and Equipped labels establish the current state. Review Loadout describes the next step. These relative traits are illustrative design content, not game balance specifications.","focus":"2026 proposal · readable trade-offs and a predictable next action."},{"src":"vanguard/loadout.png","generated":true,"label":"Loadout comparison","title":"Inspect freely. Equip deliberately.","note":"The current halberd, previewed poleaxe, and locked glaive use explicit text states. Side-by-side traits explain what changes. Equip Poleaxe commits the choice; Cancel Preview retains the halberd. The lock explains its example rank requirement instead of offering an unavailable action.","focus":"2026 proposal · separate inspection, availability, and commitment."},{"src":"vanguard/deployment.png","generated":true,"label":"Deployment review","title":"One last check before the battle.","note":"The review brings team, class, equipment, and match context together. Loadout updated confirms the completed change. Edit Loadout provides a return path, and Deploy is the explicit join action. Spectate remains secondary. The interactive concept also explores cancel and join-failure recovery.","focus":"2026 proposal · confirm the selection, then start the transition."}]},
{"id": "fintech", "name": "Fintech · Current", "title": "Confidence before confirmation.", "category": "Product UI", "context": "Wallet & exchange · Product design", "originalPeriod": "2026", "dateKind": "Independent concept", "conceptLabel": "2026 · Independent concept", "dateBasis": "New portfolio exploration informed by prior fintech experience; not recovered client work", "summary": "A fresh exploration of wallet and exchange design informed by my fintech experience. Current is a fictional product: a calm balance overview, a deliberate purchase flow, and clear recovery when a quote expires.", "tags": ["Fintech UI", "Transaction clarity", "Error recovery"], "frames": [{"src": "products/wallet.png", "generated": true, "label": "Wallet & purchase", "title": "Make the commitment understandable", "note": "Three mobile screens connect balances, amount entry, and purchase review. CAD spent, BTC received, and the fee remain distinct. Review is a separate step before confirmation; all prices are illustrative.", "focus": "Design intent · make cost and commitment easy to explain."}, {"src": "products/exchange.png", "generated": true, "label": "Exchange & recovery", "title": "An expired quote is a recoverable state", "note": "The exchange keeps the draft visible while an expired quote blocks confirmation. Refresh should return the user to review with the updated total; it must never place an order automatically.", "focus": "Design intent · preserve the draft, renew consent."}]},
{"id": "cyber", "name": "Cybersecurity · Signal", "title": "Turn curiosity into capability.", "category": "Product UI", "context": "Cybersecurity learning · Product design", "originalPeriod": "2026", "dateKind": "Independent concept", "conceptLabel": "2026 · Independent concept", "dateBasis": "New portfolio concept inspired by cybersecurity work; fictional learning platform", "summary": "Signal Academy explores how game design can support cybersecurity learning. A clear learning path leads into a safe practice lab, where evidence, explanations, and retry opportunities matter more than speed or leaderboard rank.", "tags": ["Learning experience", "Gamification", "Evidence-led feedback"], "frames": [{"src": "products/academy.png", "generated": true, "label": "Learning dashboard", "title": "Make the next useful step obvious", "note": "A resumable mission sits above the wider learning path. Skill labels explain the value of each exercise, while XP supports progress without becoming the primary goal. Locked stages should explain their prerequisite.", "focus": "Design intent · reward understanding, not hurried completion."}, {"src": "products/lab.png", "generated": true, "label": "Practice & feedback", "title": "Show why an answer works", "note": "A simulated inbox and evidence notebook share the workspace. The submitted assessment receives a specific explanation, then leads into a debrief. Fictional example domains keep the exercise clearly separated from real email.", "focus": "Design intent · connect each conclusion to observable evidence."}]},
{"id":"hockey","name":"Hockey · FACE/OFF","title":"Own the next shift.","category":"Concepts","context":"Independent sports concept · Hockey","originalPeriod":"2026","dateKind":"AI-assisted concept","dateBasis":"Created for this portfolio in 2026; not commissioned or endorsed by EA","summary":"A console hockey concept pairing a cinematic club hub with focused line management. Fictional teams and athletes support an independent exploration of AAA sports UI, with explicit preview and apply states.","tags":["Sports UI art","Controller-first UX","AI-assisted design"],"frames":[{"src":"sports/hockey-hub.png","generated":true,"label":"Club hub","title":"Give the next game priority","note":"The athlete creates energy while the primary tile answers the practical questions: who is playing, what mode is selected, and where to start. Line management and training stay available as secondary paths.","focus":"Design hypothesis · help returning players enter a game without scanning every mode."},{"src":"sports/hockey-lineup.png","generated":true,"label":"Line management","title":"Compare before committing","note":"The rink connects each player to a position. A comparison panel keeps the selected starter and replacement in the same view. The swap remains a preview until Apply; Cancel should restore the previous line.","focus":"Design hypothesis · separate selection, preview, and a saved lineup."}]},
{"id":"soccer","name":"Soccer · TOUCHLINE","title":"Make your next move.","category":"Concepts","context":"Independent sports concept · Soccer","originalPeriod":"2026","dateKind":"AI-assisted concept","dateBasis":"Created for this portfolio in 2026; not commissioned or endorsed by EA","summary":"A soccer concept connecting match preparation to squad management. A cinematic match hub establishes the club identity; a recovery screen shows how to resolve an empty starting position without losing the rest of the team.","tags":["Sports UI art","Squad management","Error recovery"],"frames":[{"src":"sports/soccer-hub.png","generated":true,"label":"Match hub","title":"Confidence before kickoff","note":"The focused Kick Off tile identifies the fixture and offline mode. A readiness message supports the primary action. Squad management is one level away, keeping preparation connected to playing.","focus":"Design hypothesis · players should know what they are about to launch."},{"src":"sports/soccer-squad.png","generated":true,"label":"Squad recovery","title":"Name the blocker. Offer the fix.","note":"The missing striker is identified at the position and in the readiness status. A candidate panel offers an immediate correction while preserving the rest of the squad. Starting a match stays unavailable until the required lineup is complete.","focus":"Design hypothesis · keep recovery in context instead of sending players through a generic error dialog."}]},
  {
    id:'squad', title:'Keep the faction. Make the choice clear.', name:'SQUAD concepts', category:'Game UI', context:'SQUAD · Design concepts',
    originalPeriod:'2022–2025', dateBasis:'Offworld studio period from resume; exact original concept date not recorded',
    summary:'A military customization concept built around faction identity, equipment previews, and ownership states. The original design anchors three new companion mockups in the same visual language.',
    tags:['Faction navigation','Customization UX','Visual hierarchy'],
    frames:[
      {src:'weapon-skins.png',label:'Original customization',title:'Identity stays in view',note:'The persistent flag strip keeps the faction visible while the player browses skins. A large equipment preview supports inspection; labels distinguish owned, equipped, and locked items. The source also contains placeholder weapon-name inconsistencies to resolve before implementation.',focus:'Keep faction, selection, and equipped state distinct.'},
      {src:'squad/faction-selection.png',generated:true,label:'Faction overview',title:'Orient before asking for a choice',note:'This new companion concept gives the selected faction a strong visual identity before moving into equipment. A quiet information area balances the soldier and flag, while one primary action continues the journey.',focus:'Proposed extension · establish context before customization.'},
      {src:'squad/vehicle-preview.png',generated:true,label:'Vehicle preview',title:'Carry the system across equipment types',note:'The proposed vehicle screen carries the original thumbnail grid, flag navigation, yellow selection outline, and large preview into a new category. Ownership labels provide a second cue alongside color.',focus:'Proposed extension · reuse familiar navigation and status cues.'},
      {src:'squad/equip-confirmation.png',generated:true,label:'Confirm equipment',title:'Preview freely. Commit deliberately.',note:'A proposed confirmation layer names the selected cosmetic and faction while preserving the preview behind it. Cancel keeps the current equipment; confirmation should lead to an explicit equipped state.',focus:'Proposed extension · make the scope of a change clear.'}
    ]
  },
  {
    id: 'mechwarrior', title: 'A cockpit for complex decisions.', name: 'MechWarrior 5', category: 'Game UI', context: 'Piranha Games · UX / UI',
    originalPeriod:'2016–2018', dateBasis:'Piranha studio period; individual screen dates not recorded',
    summary: 'A connected set of interfaces for choosing a destination, evaluating a contract, and preparing a mech for the next mission.',
    tags: ['Information hierarchy', 'Systems design', 'Unreal Engine'],
    frames: [
      {src:'mw5-starmap.png', title:'See the strategic picture', label:'Star map', note:'The planetary map is the focal point, with navigation and supporting information around its edges. Spatial relationships remain visible while the player explores destinations.', focus:'A complex world, one point of orientation.'},
      {src:'mw5-mission.png', title:'Turn a destination into a decision', label:'Mission briefing', note:'Mission details, terrain, and the selected squad share one screen. The player can review the conditions of the contract alongside the resources they will take into it.', focus:'Keep the context beside the commitment.'},
      {src:'mw5-mechbay.png', title:'Make maintenance tangible', label:'Mech bay', note:'Component labels anchor to the mech itself. The surrounding panels expose repair status, cost, and time, connecting an abstract maintenance decision to a visible part of the machine.', focus:'Connect system data to the thing it describes.'},
      {src:'s-image21.png', title:'Compare the next opportunity', label:'Planet details', note:'A persistent navigation frame holds mission listings, planetary information, and supporting statistics. The interface moves from the broad map to a detailed comparison without changing its visual language.', focus:'Preserve orientation as information gets denser.'}
    ]
  },
  {
    id:'stardust', title:'The journey behind the interface.', name:'Stardust Canvas', category:'UX process', context:'UX Magicians · Mobile product UX',
    originalPeriod:'2020–2021', dateKind:'Original design', dateBasis:'Original design period confirmed by Remi',
    summary:'A mobile experience connecting discovery, play, creative expression, and sharing. The original UX maps and component work show how the screens fit together.',
    tags:['User journeys','Information architecture','UI components'],
    frames:[
      {src:'stardust-flowchart.png',title:'Connect the whole experience',label:'User journey',note:'The flow traces discovery into play, earned stars, painting, rewards, and sharing. Both win and loss states are represented, making the routes between activities visible.',focus:'Design the transitions as carefully as the screens.'},
      {src:'s-image121.png',title:'Make the return paths explicit',label:'Sitemap',note:'The sitemap separates the main destinations from the activity loop. Return paths connect painting, rewards, and sharing back into the wider product rather than leaving them as isolated endpoints.',focus:'A destination is only useful if people can find their way back.'},
      {src:'s-image122.png',title:'Give the journey a shared vocabulary',label:'Components',note:'Cards, controls, icons, decorative elements, and colour references are collected on one board. These repeated elements link the different parts of the experience visually.',focus:'Consistency across many moments of interaction.'},
      {src:'s-image120.png',title:'Define the voice of the interface',label:'Typography',note:'The typography sheet pairs a decorative display face with a simpler supporting face. The distinction gives expressive headings and functional interface text different jobs.',focus:'Personality for the brand. Clarity for the task.'}
    ]
  },
  {
    id:'multiplayer',title:'Before the match, clarity comes first.',name:'Multiplayer UX explorations',category:'UX process',context:'Layout studies · Visual development',
    summary:'From layout studies to full-color visual concepts: character selection, party readiness, mode comparison, and matchmaking. Compare each original with its new AI-assisted refinement, then explore the UX behind it.',
    originalPeriod:'2020–2021', dateKind:'Original design', dateBasis:'Original design period confirmed by Remi',
    tags:['Interaction states','Wireframing','Decision hierarchy'],
    frames:[
      {renderSrc:'multiplayer-color/character-selection.png',src:'s-image33.png',title:'Balance the roster and the individual',label:'Character selection',note:'The roster supports comparison while a larger character presentation provides a focal point. Role and ability information sits close to the choice the player is making.',focus:'Browse broadly, then inspect one choice.'},
      {renderSrc:'multiplayer-color/ability-detail.png',src:'s-image43.png',title:'Reveal detail when it is needed',label:'Ability detail',note:'An expanded ability description adds context inside the selection screen. The character and roster remain visible, so the player can inspect a capability without losing the selection task.',focus:'More information without a separate journey.'},
      {renderSrc:'multiplayer-color/party-lobby.png',src:'s-image49.png',title:'Give the lobby a clear centre',label:'Party lobby',note:'Party slots and readiness occupy the centre; social controls sit below, with store and progression content at the sides. The layout separates the shared task from secondary destinations.',focus:'Make the group’s next action easy to locate.'},
      {renderSrc:'multiplayer-color/mode-selection.png',src:'s-image63.png',title:'Compare modes in one place',label:'Mode selection',note:'The mode-selection study combines imagery, short descriptions, and attribute icons in a repeated card structure. Players can compare options before confirming a mode.',focus:'Use a repeated structure for comparable choices.'},
      {renderSrc:'multiplayer-color/match-found.png',src:'s-image66.png',title:'Signal the change of state',label:'Match found',note:'A large match-found message and countdown take priority over the softened lobby. The screen makes the transition from preparation to play unmistakable.',focus:'When the state changes, the hierarchy should change too.'}
    ]
  },
  {
    id:'mobile',title:'Explore the options. Build the system.',name:'Mobile UI & iteration',category:'UX process',context:'Portfolio archive · Mobile design studies',
    summary:'Original exploration boards show alternative visual directions, related screens, and reusable controls. This is the work between an initial direction and a coherent interface.',
    originalPeriod:'2020–2021', dateKind:'Original design', dateBasis:'Original study period confirmed by Remi',
    tags:['Visual exploration','Component design','Mobile UI'],
    frames:[
      {src:'s-image84.png',title:'Put alternatives side by side',label:'Style explorations',note:'Five visual directions are presented across related game and pause screens. The board explicitly proposes testing the mockups; no test results or winning variant are claimed here.',focus:'Compare a direction across a system, not just one screen.'},
      {src:'s-image87.png',title:'Carry the direction through the journey',label:'Screen family',note:'Menu, progression, and gameplay layouts are shown together. Shared colour, typography, and control treatments make it possible to inspect consistency across the screen family.',focus:'A visual direction has to survive more than a hero screen.'},
      {src:'s-image92.png',title:'Make the pieces reusable',label:'Component board',note:'Screen compositions sit alongside extracted buttons, icons, and repeated elements. The board exposes the building blocks as well as their use in context.',focus:'Connect the component to the screen that needs it.'},
      {src:'s-image112.png',title:'Show an interaction over time',label:'Attack flow',note:'A separate mobile strategy study follows deployment, troops in motion, an outcome message, and a return to the map. It shows how feedback carries the player through an action.',focus:'The interaction is a sequence, not a single mockup.'}
    ]
  },
  {
    id:'cards',title:'A collection built for making choices.',name:'Fantasy card systems',category:'Game UI',context:'Gogii Games · Game UI',
    summary:'Collection, deck-building, and card-detail interfaces that bring artwork, comparison, and composition into the same visual language.',
    originalPeriod:'2009–2013', dateBasis:'Gogii studio period; individual screen dates not recorded',
    tags:['Collection UX','Information density','Visual design'],
    frames:[
      {src:'fantasy-deckbuilder.png',title:'Keep the collection and the deck together',label:'Deck builder',note:'A card grid provides the browsing area while the current deck stays visible in a sidebar. The arrangement keeps individual choices in the context of the collection being built.',focus:'Keep the result of a choice visible while making the next one.'},
      {src:'s-image156.png',title:'Inspect without losing context',label:'Card detail',note:'An expanded card adds artwork and descriptive information beside the collection and deck. The surrounding layout preserves the relationship between one card and the larger composition.',focus:'Zoom into the detail without abandoning the task.'},
      {src:'fantasy-cards.png',title:'Let the characters lead',label:'Hero collection',note:'Large character portraits create the primary selection targets. Persistent navigation and resource information frame the collection without competing with the artwork.',focus:'Use visual hierarchy to support emotional choice.'}
    ]
  },
  {
    id:'motion',title:'Make the first interaction set the tone.',name:'Motion & AI-assisted concepts',category:'Concepts',context:'Personal explorations · Concept work',
    summary:'Short motion studies exploring atmosphere, inventory, and menu identity. These are personal concepts, separate from the studio work and UX artifacts above.',
    originalPeriod:'2020–2021', dateKind:'Original concept', dateBasis:'Original concept period confirmed by Remi',
    tags:['Motion design','Rapid concepts','AI-assisted exploration'],
    frames:[
      {src:'videos/hiphopvid.mp4',poster:'hiphopvid-poster.jpg',type:'video',title:'A menu with a sense of place',label:'Hip Hop Rap Battle',note:'The concept puts a bold menu alongside a live performance atmosphere. Motion and lighting communicate the genre before a player makes a selection.',focus:'The menu is also the opening scene.'},
      {src:'videos/fpsscifi.mp4',poster:'fpsscifi-poster.jpg',type:'video',title:'Give inventory a physical presence',label:'Sci-fi inventory',note:'A character-centred inventory study combines equipment information with a moving background. The concept explores the balance between atmosphere and readable interface elements.',focus:'World-building and usability share the same frame.'},
      {src:'videos/potion.mp4',poster:'potion-poster.jpg',type:'video',title:'Bring browsing and buying together',label:'Magical arsenal',note:'The concept explores inventory and shop actions in a shared space, with item presentation and ownership information supporting the browsing experience.',focus:'Explore a simpler relationship between related tasks.'}
    ]
  }
];
